### ISSUE TITLE
MiKTeX 22.8.28 Portable is missing `pdflatex`

### ISSUE THREAD

**Issue by IlonkaP** [MiKTeX/miktex#1183]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
- [x] MiKTeX is up-to-date
    - Yes, on version 22.8.28.
- [x] This is not a known bug
    - I have been searching this GitHub and Google now for hours. I couldn't find anything that would have helped me.
- [x] MiKTeX installation report
    - [miktex-portable-complete-report.txt](https://github.com/MiKTeX/miktex/files/9581590/miktex-portable-complete-report.txt)
    - [miktex-portable-basic-report.txt](https://github.com/MiKTeX/miktex/files/9581592/miktex-portable-basic-report.txt)
    - [miktex-portable-essential-report.txt](https://github.com/MiKTeX/miktex/files/9581593/miktex-portable-essential-report.txt)
- [x] MiKTeX history
    - Not applicable.

I am on Windows 10 20H2 (OS Build 19042.1889) using cmd.exe as commandline.

I got the MiKTeX Setup Utility from https://miktex.org/download.

I used the following command to create a local package repository:
```
miktexsetup_standalone.exe --verbose --local-package-repository=D:\MiKTeX\packages\complete --package-set=complete download
```

I installed a portable instance of MiKTeX complete afterwards using command:
```
miktexsetup_standalone.exe --verbose --local-package-repository=D:\MiKTeX\packages\complete --package-set=complete --portable=D:\MiKTeX\complete --use-registry=no --modify-path=no install
```

I have run `D:\MiKTeX\complete\texmfs\install\miktex\bin\x64\miktex-console.exe` and checked for updates. None where available.

**Actual issue**:
I cannot find `pdflatex.exe` inside `D:\MiKTeX\complete\texmfs\install\miktex\bin\x64` (or anywhere else inside `D:\MiKTeX\complete` for that matter) and for the life of me I cannot find out why that is or what I have to do/change in my steps to get it there.

**Note**: I don't know, if pdflatex is supposed to be part of the `essential` variant, but it is missing for that one as well as for `basic` too when using the same steps as above for `complete`.

**Comment by BeerStud** [comment]
Evidently, something is broken with the MiKTeX installers.

["pdflatex.exe" missing from "Windows net installer 64"](https://github.com/MiKTeX/miktex/issues#:~:text=%22pdflatex.exe%22%20missing%20from%20%22Windows%20net%20installer%2064%22)

**Comment by edocevoli** [comment]
This has been fixed now.

**Comment by IlonkaP** [comment]
@edocevoli For me the issue isn't fixed, it even got worse. Now several whole directories are missing. For example, the whole `texmfs/install/bin` directory is missing.
