### ISSUE TITLE
Empty file error when trying to complete the setup on a Mac

### ISSUE THREAD

**Issue by sephill27** [MiKTeX/miktex#491]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
After downloading MiKTeX, adding it to applications on my Mac, when I click the icon and try to complete the setup, I get an error message that the file os empty. I have downloaded the program twice and get the same error.

**Comment by edocevoli** [comment]
Sorry that it doesn't work for you. If I understand you correctly, you have:

1. download the `.dmg` file
1. double-clicked the `.dmg` file
1. dragged the MiKTeX Console icon onto the Applications folder
1. double-clicked the MiKTeX Console icon
1. clicked `Finish private setup`

Please attach a screenshot of the error message.

**Comment by sephill27** [comment]
This is what I get when I try to complete the setup
Thanks,
Sharon
________________________________

**Comment by edocevoli** [comment]
???

**Comment by sephill27** [comment]
After adding MikTeX to applications, when I click it to complete the setup, I get the first attached screenshot, when I click Yes, I get the second window. If I hit Copy Info button, what is on the clipboard is the third attachment. Not sure what the problem is.
________________________________

**Comment by edocevoli** [comment]
There are no screenshots ☹️

**Comment by edocevoli** [comment]
It seems that you are using the E-Mail interface. That does not work so good and it exposes your E-Mail address to the world.

I would recommend that you

1. visit the issue page https://github.com/MiKTeX/miktex/issues/491
1. write a comment and attach the screenshots

**Comment by sephill27** [comment]
<img width="494" alt="Screen Shot 2020-03-19 at 12 05 28 PM" src="https://user-images.githubusercontent.com/60005713/77096181-f6a5bd00-69dc-11ea-9b49-47e8f05e78cb.png">
<img width="448" alt="Screen Shot 2020-03-19 at 12 01 47 PM" src="https://user-images.githubusercontent.com/60005713/77096191-f9081700-69dc-11ea-8fb5-459ae10cec30.png">
<img width="363" alt="Screen Shot 2020-03-19 at 12 01 31 PM" src="https://user-images.githubusercontent.com/60005713/77096194-fad1da80-69dc-11ea-893b-666325dfcf88.png">
After adding MikTeX to applications, when I click it to complete the setup, I get the first attached screenshot, when I click Yes, I get the second window. If I hit Copy Info button, what is on the clipboard is the third attachment. Not sure what the problem is.

**Comment by edocevoli** [comment]
Okay, that's annoying. You can safely remove everything under `/Users/.../Library/Application Support/MiKTeX`. This should fix it.

**Comment by sephill27** [comment]
I tried removing everything under what you suggested and it still won't run. It may be on Apple's side with the Catalina version of OS. It may be preventing the program from opening and running properly.
Thanks for your help,
Sharon

**Comment by sephill27** [comment]
I have gotten MikTex to work, thanks for your help.

**Comment by edocevoli** [comment]
Thank you, @sephill27 . I leave the ticket open for a few days because the bug (empty filename database) has been fixed and the fix will be available soon.

**Comment by auromg** [comment]
Thanks but still don't know what I have to do.

**Comment by edocevoli** [comment]
> Thanks but still don't know what I have to do.

Either help us to understand reproduce the issue, or provide information which makes it possible to find a software bug. Please don't assume that we are super intelligent. We need some help to find/fix the issue.

**Comment by auromg** [comment]
Apologies for my impatience.
I do appreciate your help.
Aurora

**Comment by auromg** [comment]
I don't know if this may help.


The MikTeX console crushes:

[image: Captura de pantalla 2021-05-05 a las 22.45.25.png]

[image: Captura de pantalla 2021-05-05 a las 22.45.49.png]

When I try to compile with pdflatex I get this message:



pdflatex: File is empty. pdflatex: Data:
path="/Users/j.../Library/Application
Support/MiKTeX/texmfs/data/miktex/data/le/941f039eeecd4c1a5b73119da11389c6.fndb-5"


Thank you very much.

**Comment by auromg** [comment]
This is what I get with any of the following command lines 
initexmf --force --mklinks --admin
initexmf --force --mklinks
initexmf --mklangs

File is empty.
Data: path="/Users/...Library/ApplicationSupport/MiKTeX/texmfs/data/miktex/data/le/941f039eeecd4c1a5b73119da11389c6.fndb-5"
Source: Libraries/MiKTeX/Core/MemoryMappedFile/unx/unxMemoryMappedFile.cpp:108
File is empty.
Info: path="/Users/.../Library/ApplicationSupport/MiKTeX/texmfs/data/miktex/data/le/941f039eeecd4c1a5b73119da11389c6.fndb-5"
Source: Libraries/MiKTeX/Core/MemoryMappedFile/unx/unxMemoryMappedFile.cpp
Line: 108

Sorry, but "MiKTeX Configuration Utility" did not succeed.
log4cxx: No appender could be found for logger (initexmf).
log4cxx: Please initialize the log4cxx system properly.
