### ISSUE TITLE
miktex-misc: package is broken

### ISSUE THREAD

**Issue by harriott** [MiKTeX/miktex#855]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Following on from MiKTeX/miktex/discussions/851, `miktex-misc` doesn't appear to fully update, and remains "broken".

- Windows 10 Pro version 20H2 (OS build 19042.1055)
- `basic-miktex-21.6-x64.exe` > (only for me)

Immediately after installation, `MiKTeX Console > Check for updates` gets me 7 updates including `miktex-misc`, which I allow to update, then I get a popup stating, "MiKTeX Console needs to be closed." When I rerun it to `Check for updates` again, `miktex-misc` appears again, flagged "to be repaired".  Each subsequent time I `Check for updates`, `miktex-misc` reappears and I get the same messages in my `~\AppData\Local\MiKTeX\miktex\log\miktex-console.log`:

```
2021-06-24 14:54:31,552+0200 WARN  miktex-console.packagemanager - package miktex-misc verification failed: some files have been modified
2021-06-24 14:54:31,552+0200 WARN  miktex-console.packagemanager - expected digest: cf4a1581e6df82756f88dfde8ea50d00
2021-06-24 14:54:31,552+0200 WARN  miktex-console.packagemanager - computed digest: fff75277bc7c320726a4c67a8781f916
2021-06-24 14:54:31,552+0200 WARN  miktex-console.packagemanager - miktex-misc: package is broken
```
[ConfigReport.txt](https://github.com/MiKTeX/miktex/files/6711067/ConfigReport.txt)

**Comment by edocevoli** [comment]
Thank you for the report. The problem is not reproducible on my system, i.e., a fix cannot be made available. The log snippet indicates that you are working with an outdated package database. But without more context, it is hard to tell what has gone wrong.

**Comment by u-fischer** [comment]
I have problems with miktex-misc now too. Everytime I look for an update it is in the list as "must be repaired".  There is also a question on tex.sx about this https://tex.stackexchange.com/questions/602555/problems-updating-the-miktex-misc-file

**Comment by edocevoli** [comment]
I have re-created the package archive file `miktex-misc.tar.lzma` and the data base archive files `miktex-zzdb*.tar.lzma`. If something was broken, it should be fixed now. We can check for updates tomorrow and see what happens...

**Comment by joaoluisbh** [comment]
> I have re-created the package archive file `miktex-misc.tar.lzma` and the data base archive files `miktex-zzdb*.tar.lzma`. If something was broken, it should be fixed now. We can check for updates tomorrow and see what happens...

Hi edocevoli. Same problem here. It still didn't work after you made the changes you mentioned.

**Comment by kiravi** [comment]
Another one here, same problem on Windows 10:

1. Removing package and installing --> does not fix it.
2. Update package database does not do it.
3. Deleting all miktex install --> cleaning up and doing it again does not fix it.

Installing for everyone, and running update on console as admin does not fix it.

**Comment by joaoluisbh** [comment]
I just made another attempt. It worked, thanks

**Comment by harriott** [comment]
`miktex-misc` successfully updated for me now, thanks.
